### ISSUE TITLE
Arial is not very bold in some browser windows

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/mirlo#1283]
Firefox on Linux Mint:

![Image](https://github.com/user-attachments/assets/ec195808-c864-4c31-bf97-40fc6bf29d8e)

Worx Printing is bold here. However, in other browsers it looks fine

![Image](https://github.com/user-attachments/assets/3637baff-3180-4f7a-9a4b-26b878291f1e)

Here's a pen to try some stuff out.

https://codepen.io/simonv3/pen/PwqLqyW

**Comment by timglorioso** [comment]
Thanks for opening this.

I notice these are different fonts. The top one looks like Arial and the bottom one looks like Liberation Sans. As far as I know, we don't force downloading of fonts where Arial is used. I suspect there's some version of Arial installed on that system that either doesn't have a bold face, or with a less-bold bold face.

**Comment by timglorioso** [comment]
@simonv3 are both screenshots from the same computer? If not, it might be an issue with fonts installed on the computer in the first screenshot (and then we could close this issue).

**Comment by timglorioso** [comment]
It's a small issue, but curiosity gets the better of me. At this point we have two versions of Linux Mint (@Cwpute the second) with different results in Mirlo, the same code.

@simonv3 assuming you're also curious 😄 what does this output for you?

```sh
fc-match Arial:weight=bold
```

On Debian I get `LiberationSans-Bold.ttf: "Liberation Sans" "Bold"`

**Comment by simonv3** [comment]
```
$ fc-match Arial:weight=bold
arial.ttf: "Arial" "Regular"
```

**Comment by timglorioso** [comment]
Thanks both, feels good to get to the bottom of this. Warning: weeds afoot, ignore at your own discretion.

Simon, it looks like your system has Arial installed, but without a bold face, so it's falling back to Regular. Because there's no real bold, browsers are applying ["faux bold"](https://alistapart.com/article/say-no-to-faux-bold/). Firefox's attempt is a little less convincing than Chrome's.

As you suggested, `@font-face` might help here. Thinking out loud:

```css
@font-face {
  font-family: "Arial";
  font-weight: regular;
  ...
}

@font-face {
  font-family: "Arial";
  font-weight: bold;
  src:
    /* Try to get Arial first */
    local("Arial Bold"),
    local("Arial-Bold"),
    local("Arial-BoldMT"),
    /* Fall back to something else */
    local( ... whatever this could be )
}
```

This would at least get us to have a fallback if Arial Bold doesn't exist. A problem with this approach is then we might end up rendering two different fonts: if Arial Regular is available locally but Arial Bold isn't, we'd use non-Arial bold. It doesn't seem like CSS makes it easy to handle the use case of ensuring local availability of multiple styles of a font.

I also learned here that systems can try to provide a different font than requested by the CSS. Liberation Sans is silently matched by Arial. As a CSS author, I find this unexpected and undesirable. So there's fallbacks in CSS that is visible in our code as the `font-family` stack, and the fallbacks in the system that is a black box, both from the perspective of our code and my current understanding :)
