### ISSUE TITLE
Docker dev issues on arm64 macOS

### ISSUE THREAD

**Issue by peterklingelhofer** [funmusicplace/mirlo#806]
The Docker back-end seems a bit trickier to spin up than I would hope.

Doing `docker compose watch` yields a bunch of errors on the initial startup that you need to chmod through:

`Error response from daemon: error while creating mount source path '~/Dev/mirlo/data/pgsql_backups': chown ~/Dev/mirlo/data/pgsql_backups: permission denied`

I was able to resolve it by:
`chmod -R u+rwx ~/Dev/mirlo/data/pgsql_backups`

You'll then get `Error response from daemon: error while creating mount source path '~/Dev/mirlo/data/pgsql': chown ~/Dev/mirlo/data/pgsql: permission denied`, and then you can chmod that and you'll proceed to have to do it about 10-15 times.

Having done that, running watch seems to work:
```sh
> docker compose watch
[+] Building 3.0s (34/34) FINISHED docker:rancher-desktopbackground internal] load metadata for d  2.6s
 => [api internal] load build definition from  0.0s
 => => transferring dockerfile: 1.15kB         0.0s
 => [background internal] load metadata for d  2.6s
 => [background internal] load metadata for d  2.7s
 => [api internal] load .dockerignore          0.0s
 => => transferring context: 149B              0.0s
 => [api internal] load build context          0.1s
 => => transferring context: 177.00kB          0.1s
 => [background ffmpeg 1/1] FROM docker.io/jr  0.0s
 => [background base  1/14] FROM docker.io/li  0.0s
 => CACHED [background base  2/14] COPY --fro  0.0s
 => CACHED [background base  3/14] RUN apt-ge  0.0s
 => CACHED [background base  4/14] RUN apt-ge  0.0s
 => CACHED [background base  5/14] WORKDIR /v  0.0s
 => CACHED [background base  6/14] RUN corepa  0.0s
 => CACHED [background base  7/14] RUN corepa  0.0s
 => CACHED [api base  8/14] COPY package.json  0.0s
 => CACHED [api base  9/14] COPY prisma/packa  0.0s
 => CACHED [api base 10/14] COPY client/packa  0.0s
 => CACHED [api base 11/14] RUN --mount=type=  0.0s
 => CACHED [api base 12/14] COPY prisma ./pri  0.0s
 => CACHED [api base 13/14] RUN yarn prisma:b  0.0s
 => CACHED [api base 14/14] COPY . .           0.0s
 => [api] exporting to image                   0.0s
 => => exporting layers                        0.0s
 => => writing image sha256:2a468e39f32a3d4df  0.0s
 => => naming to docker.io/library/mirlo-api   0.0s
 => [api] resolving provenance for metadata f  0.0s
 => [background internal] load build definiti  0.0s
 => => transferring dockerfile: 1.15kB         0.0s
 => [background internal] load .dockerignore   0.0s
 => => transferring context: 149B              0.0s
 => [background internal] load build context   0.0s
 => => transferring context: 177.00kB          0.0s
 => CACHED [background base  8/14] COPY packa  0.0s
 => CACHED [background base  9/14] COPY prism  0.0s
 => CACHED [background base 10/14] COPY clien  0.0s
 => CACHED [background base 11/14] RUN --moun  0.0s
 => CACHED [background base 12/14] COPY prism  0.0s
 => CACHED [background base 13/14] RUN yarn p  0.0s
 => CACHED [background base 14/14] COPY . .    0.0s
 => [background] exporting to image            0.0s
 => => exporting layers                        0.0s
 => => writing image sha256:565e8b706fb5a15d7  0.0s
 => => naming to docker.io/library/mirlo-back  0.0s
 => [background] resolving provenance for met  0.0s
[+] Running 5/5
 ✔ Container blackbird-pgsql       Started     0.6s 
 ✔ Container blackbird-redis       Started     0.5s 
 ✔ Container blackbird-minio       Started     0.5s 
 ✔ Container blackbird-background  Started     0.9s 
 ✔ Container blackbird-api         Started     0.0s 
Watch enabled
```

But then when you go to localhost:3000/docs, there are no Swagger docs running on port 3000. Tried doing `FROM --platform=linux/amd64` for the images in the `Dockerfile` but didn't seem to help.

<img width="1321" alt="Screenshot 2024-08-15 at 5 58 27 AM" src="https://github.com/user-attachments/assets/4ff78973-9fff-4fa3-8f9e-e55583b83a62">

```sh
> docker logs blackbird-pgsql

chown: /var/lib/postgresql/data: Permission denied
```

```sh
> docker inspect blackbird-pgsql

[
    {
        "Id": "b8919b53a97bf756d8ddf6ee64f6ab43434c2e510f16c956812be46584409bcd",
        "Created": "2024-08-15T10:56:34.78729168Z",
        "Path": "docker-entrypoint.sh",
        "Args": [
            "postgres"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2024-08-15T10:56:35.327424722Z",
            "FinishedAt": "2024-08-15T10:56:35.351913388Z",
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 0,
                "Log": []
            }
        },
        "Image": "sha256:9a0f81eda084797416d309cf0b689265d412e5b7c86e67f7695333428abaac0d",
        "ResolvConfPath": "/var/lib/docker/containers/b8919b53a97bf756d8ddf6ee64f6ab43434c2e510f16c956812be46584409bcd/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/b8919b53a97bf756d8ddf6ee64f6ab43434c2e510f16c956812be46584409bcd/hostname",
        "HostsPath": "/var/lib/docker/containers/b8919b53a97bf756d8ddf6ee64f6ab43434c2e510f16c956812be46584409bcd/hosts",
        "LogPath": "/var/lib/docker/containers/b8919b53a97bf756d8ddf6ee64f6ab43434c2e510f16c956812be46584409bcd/b8919b53a97bf756d8ddf6ee64f6ab43434c2e510f16c956812be46584409bcd-json.log",
        "Name": "/blackbird-pgsql",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "~/Dev/mirlo/data/pgsql:/var/lib/postgresql/data:rw",
                "~/Dev/mirlo/data/pgsql_backups:/backups:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "mirlo_api-network",
            "PortBindings": {
                "5432/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5434"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/1259fcdef1c3d2ed999ccbaad55d1528811fee28fa47b032f598b4af613de168-init/diff:/var/lib/docker/overlay2/a1064859bf9bba0029f2540e5a92722b96f9c45bcdfe0772dccf6d6deb395657/diff:/var/lib/docker/overlay2/9dff55047c199239527838a725008341a55f217ed5940732bb0e395230d74386/diff:/var/lib/docker/overlay2/7f77f9decbe3f3e8ae2ebd108b743c6c72fc9adf2bcb0c33c0d75be95d96e8f3/diff:/var/lib/docker/overlay2/2b120a46e77da2f4e80f3c9ff4d69309524f08b42e751931f5905b09a32111a1/diff:/var/lib/docker/overlay2/1ab87e7d98b9893b440b949c02a5f4027f3b22b34909dd62c63f8f0bd65d998b/diff:/var/lib/docker/overlay2/cbcfe4fcf0cf0f1b9db3b3b58028db0db8227802c0ef4becfa6a8d19da7a8dd9/diff:/var/lib/docker/overlay2/b814eaf0691cd315a873639145df1cf76f5524977a2acd48526821f1812df04f/diff:/var/lib/docker/overlay2/6f97738221a15ed34543c0391a9503d7df3d401c4054745aa420d73cbc014205/diff:/var/lib/docker/overlay2/243fe355d2aa16fd8376dce9e96bd499b95204dfd86ca06c885dc189bb613e50/diff",
                "MergedDir": "/var/lib/docker/overlay2/1259fcdef1c3d2ed999ccbaad55d1528811fee28fa47b032f598b4af613de168/merged",
                "UpperDir": "/var/lib/docker/overlay2/1259fcdef1c3d2ed999ccbaad55d1528811fee28fa47b032f598b4af613de168/diff",
                "WorkDir": "/var/lib/docker/overlay2/1259fcdef1c3d2ed999ccbaad55d1528811fee28fa47b032f598b4af613de168/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "~/Dev/mirlo/data/pgsql",
                "Destination": "/var/lib/postgresql/data",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "~/Dev/mirlo/data/pgsql_backups",
                "Destination": "/backups",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "b8919b53a97b",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "5432/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "REDIS_HOST=redis",
                "MINIO_PORT=9000",
                "API_DOMAIN=http://localhost:3000",
                "REACT_APP_API_DOMAIN=http://localhost:3000",
                "MINIO_ROOT_PASSWORD=password",
                "JWT_SECRET=test1234",
                "REDIS_PORT=6379",
                "REDIS_PASSWORD=password",
                "STATIC_MEDIA_HOST=http://localhost:3000",
                "STRIPE_KEY=",
                "POSTGRES_PASSWORD=nomads",
                "MINIO_ROOT_USER=blackbird",
                "MEDIA_LOCATION=./data/media/",
                "MINIO_HOST=minio",
                "REFRESH_TOKEN_SECRET=test1234",
                "POSTGRES_USER=nomads",
                "DATABASE_URL=postgresql://nomads:nomads@pgsql:5432/nomads?schema=public",
                "PORT=3000",
                "POSTGRES_LOCAL_MACHINE_PORT=5434",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.utf8",
                "PG_MAJOR=14",
                "PG_VERSION=14.12",
                "PG_SHA256=6118d08f9ddcc1bd83cf2b7cc74d3b583bdcec2f37e6245a8ac003b8faa80923",
                "DOCKER_PG_LLVM_DEPS=llvm15-dev \t\tclang15",
                "PGDATA=/var/lib/postgresql/data"
            ],
            "Cmd": [
                "postgres"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "pg_isready",
                    "-U",
                    "nomads"
                ],
                "Interval": 10000000000,
                "Timeout": 5000000000,
                "Retries": 5
            },
            "Image": "postgres:14-alpine",
            "Volumes": {
                "/var/lib/postgresql/data": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "195265757de93d623c17f85b8719df175e3df5159ce2dca2f20d3856897bfb9e",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "",
                "com.docker.compose.image": "sha256:9a0f81eda084797416d309cf0b689265d412e5b7c86e67f7695333428abaac0d",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "mirlo",
                "com.docker.compose.project.config_files": "~/Dev/mirlo/docker-compose.yml",
                "com.docker.compose.project.working_dir": "~/Dev/mirlo",
                "com.docker.compose.service": "pgsql",
                "com.docker.compose.version": "2.29.1"
            },
            "StopSignal": "SIGINT"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "bar",
            "SandboxKey": "/var/run/docker/netns/20b9a046c356",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "mirlo_api-network": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "blackbird-pgsql",
                        "pgsql"
                    ],
                    "MacAddress": "",
                    "NetworkID": "foo",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DriverOpts": null,
                    "DNSNames": [
                        "blackbird-pgsql",
                        "pgsql",
                        "b8919b53a97b"
                    ]
                }
            }
        }
    }
]
```

All this to say, I think we need to change the paths in the Postgres to work better with macOS. I was able to modify the `docker-compose.api.yml` file:
```yml
services:
  redis:
    container_name: blackbird-redis
    command:
      - redis-server
      - "--appendonly"
      - "yes"
      - "--requirepass=${REDIS_PASSWORD}"
    image: redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [api-network]
    ports:
      - "${REDIS_HOST_PORT:-6379}:${REDIS_PORT:-6379}"

  api:
    container_name: blackbird-api
    env_file:
      - .env
    build:
      context: .
      target: api
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      - redis
      - pgsql
      - minio
    networks: [api-network]
    ports:
      - "${APP_HOST_PORT:-3000}:3000"
    restart: unless-stopped
    volumes:
      - ${MEDIA_LOCATION:-./data/media/}incoming:/data/media/incoming
      - ${MEDIA_LOCATION:-./data/media/}downloadCache:/data/media/downloadCache
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /var/www/api/src
        - action: sync+restart
          path: ./emails
          target: /var/www/api/emails
        - action: rebuild
          path: ./prisma
          target: /var/www/api/prisma
        - action: rebuild
          path: package.json

  background:
    container_name: blackbird-background
    env_file:
      - .env
    build:
      context: .
      target: background
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      - redis
      - pgsql
      - api
      - minio
    restart: unless-stopped
    networks: [api-network]
    volumes:
      - ${MEDIA_LOCATION:-./data/media/}processing:/data/media/processing
      # - ${MEDIA_LOCATION:-./data/media/}audio:/data/media/audio
      # - ${MEDIA_LOCATION:-./data/media/}images:/data/media/images
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /var/www/api/src
        - action: sync+restart
          path: ./emails
          target: /var/www/api/emails
        - action: rebuild
          path: ./prisma
          target: /var/www/api/prisma
        - action: rebuild
          path: package.json

  minio:
    container_name: blackbird-minio
    image: minio/minio
    networks: [api-network]
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Web UI Port
    volumes:
      - minio_storage:/data
    env_file: .env
    command: server --console-address ":9001" /data

  pgsql:
    container_name: blackbird-pgsql
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      # Use named volumes for cross-platform consistency
      - pgsql_data:/var/lib/postgresql/data
      - ${PGSQL_BACKUPS_LOCATION:-./data/pgsql_backups}:/backups
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [api-network]
    ports:
      - "${POSTGRES_LOCAL_MACHINE_PORT:-5432}:5432"

networks:
  api-network:
    driver: bridge

volumes:
  minio_storage: {}
  pgsql_data: {}  # Named volume for PostgreSQL data
```

And now we see a bit more going on:
<img width="1321" alt="Screenshot 2024-08-15 at 6 26 05 AM" src="https://github.com/user-attachments/assets/1db1fa27-ee17-4091-9278-a0831340d22a">

However, still nothing going on at http://localhost:3000/docs. Any ideas?

**Comment by whalygood** [comment]
A better way to solve the permissions issue with the Postgres volume is to use a named volume instead of a bind mount.

In **docker-compose.api.yml**, for the pgsql service, change the volume mapping to read
```
    volumes:
      - pgsql_data:/var/lib/postgresql/data
      - pgsql_backups:/backups
```
and at the bottom of the file, remember to define the new named volumes
```
volumes:
  minio_storage: {}
  pgsql_data: {}
  pgsql_backups: {}
```
This sidesteps the permissions issues with the pgsql container starting up without needing any trickery with `chmod`.
---
Run a `docker compose down && docker image prune` then start the stack as follows:
`DOCKER_DEFAULT_PLATFORM=linux/amd64 docker compose watch`

![image](https://github.com/user-attachments/assets/62f5912b-2fcb-4329-b38c-61aff403fa40)
![image](https://github.com/user-attachments/assets/6e645162-4478-406b-98cc-a9e6875f0f9d)
